version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    restart: unless-stopped

  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - '1883:1883' # MQTT TCP
      - '8083:8083' # MQTT WebSocket
      - '8084:8084' # MQTT WebSocket (TLS)
      - '18083:18083' # EMQX Dashboard
    environment:
      EMQX_NAME: emqx
      EMQX_HOST: 0.0.0.0
      EMQX_ALLOW_ANONYMOUS: 'true'
      EMQX_AUTH__USER__1__USERNAME: mqttuser
      EMQX_AUTH__USER__1__PASSWORD: mqttpassword
    restart: unless-stopped

volumes:
  postgres_data:
